.gitignoreno
TKLB-OECU/Collaborative_classes_2024 pull request #4
Opened 2024-02-24 17:50 UTC by noli-noli

2024-02-24 18:04 UTC, noli-noli commented
プロンプト自体はWeb APIを通して8070ポートに送られる事を想定。
生成結果は.glfファイルをbase64にエンコードした上でレスポンスを返す。

よって、受信側ではbase64を.glfファイルにデコードする工夫が必要

2024-02-25 14:48 UTC, noli-noli commented
コンフリクトが発生している様なので、手が空いた際に修正します。

2024-02-26 12:20 UTC, Riku-21-073 commented
この様な場合はマージの承認等はしない方がよいのでしょうか？

2024-02-27 08:27 UTC, noli-noli commented
ですです。1つのファイルを同時に修正しようとして衝突(コンフリクト)している状態です。コンフリクトが解消するまで放置で大丈夫です。

2024-03-01 11:16 UTC, mu7889yoon approved these changes

2024-03-01 11:21 UTC, mu7889yoon requested changes
shap-e関連のファイルはsubmoduleにするべきと思います。

2024-03-01 11:21 UTC, mu7889yoon commented on shap-e/src/shap_e/examples/example_data/corgi.png
不要では？

2024-03-01 11:21 UTC, mu7889yoon commented on shap-e/src/shap_e/examples/sample_image_to_3d.ipynb
必要ですか？

2024-03-01 11:21 UTC, mu7889yoon commented on shap-e/src/shap_e/examples/sample_text_to_3d.ipynb
不要では？

2024-03-01 11:22 UTC, mu7889yoon requested changes
shap-e関連のファイルはsubmoduleにすると良いと思います。

2024-03-02 12:26 UTC, noli-noli commented
ご指摘感謝です。

2024-03-04 17:06 UTC, merged